[package]
name = "slh-dsa-core"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"

[dependencies]
slh-dsa = { workspace = true }
rand_core = { workspace = true }
hybrid-array = { workspace = true }
